# Generated by Django 4.1.4 on 2023-03-20 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.AlterField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(related_name='groups', to='myapp.student'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='subject',
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, help_text='Ënter student number', max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='myapp.subject'),
        ),
    ]
